package dev.linklecompanion.registry;

import dev.linklecompanion.LinkleCompanion;
import net.minecraft.core.registries.Registries;
import net.minecraft.tags.TagKey;
import net.minecraft.world.entity.EntityType;

/**
 * Tags this mod adds. They are normal data-pack tags, so other mods and data packs can add to them.
 * The files are generated by {@code datagen/ModTagProviders}.
 */
public final class ModTags {
	/** Entities Linkle will never shoot, even by accident (villagers, golems, ...). */
	public static final TagKey<EntityType<?>> NEVER_TARGET = TagKey.create(Registries.ENTITY_TYPE, LinkleCompanion.id("never_target"));
	/** Hostile entities Linkle does not bother shooting because bolts can't hurt them (endermen, breezes). */
	public static final TagKey<EntityType<?>> IGNORED_TARGETS = TagKey.create(Registries.ENTITY_TYPE, LinkleCompanion.id("ignored_targets"));

	private ModTags() {
	}
}
